language: node_js
node_js:
- 'stable'
- '7.0'
- '6.0'
- '5.0'
cache: yarn
script:
- npm run travis
env:
  global:
    secure: fDpxuHa0wucLsSfWuu19sfJdrtdH1KtYMz+vJ06eNK0eS3nUGQ8gj1ieXtIEDmKZQgSv1pcFLgYGSKeAwdYzv26y/STucfYfkGQSia7Halp1S/NkBcxW4nPvmJ+QRuJb28InyFlsdGhMoKONdgeUcMS+ocrk2rUgEiUKc+ViVAjz/LbbYHtLBTmr7fIbeGNwP+tnu9yJ/e23i4F26t0Rz7Jkvakn5WZuEqts0K05Ao4wfifv7SadUeg3tN5JuYG95T/DFibRY2sL33SZNKS3ghQ/D/apCqT7sGnm0Z0RUFeIqJ7WQyRbLuX4D5dN28J4iph5FZ8dEqEI8LDtN7xxiXY+NJLHH8NT8GXGhBkFUpwo1YxYm7oCuFqp9iRZ8FmIwp2sQCnGmVE62s9bqlitPnRYPmNaZT4zlgIRwZTtHoLT+tK+lE/w5+/WGxGT1EmhD2+gs5xWWwJ4ZMg/VB1Vl1b77fKqENiLdWlq017Uj3q2XTtFOvlkG+2diKiPdzxlRqRnDANLw7akgbohhipyK3quhyBNnoiHnKTpJYQEyoAjW7DCiTdRckvtbqdj1K0K1FD7YOBKkc05cl25jTl/BfP/orwunPNoCa0J212u/KaFiU/yIadFUQCKeRvQCcq7kj2AZSW4tXRK8tllErurB0xfXiWl2if47jGRtAfR1ns=
